CUDA_VISIBLE_DEVICES=0 python main.py --target-update 2000 \
               --T-max 100000 \
               --learn-start 1600 \
               --memory-capacity 100000 \
               --replay-frequency 1 \
               --multi-step 20 \
               --architecture data-efficient \
               --hidden-size 256 \
               --learning-rate 0.0001 \
               --evaluation-interval 1000 \
               --replay-type NERS \
               --game ms_pacman \
               --enable-cudnn